# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.50.0"

default_platform :ios

platform :ios do
#before_all do
#cocoapods
#end

desc "Creating a code signing certificate and provision profile"
lane :provision do
produce(
app_name: ‘EndlessHaiku’,
language: 'English',
app_version: '1.0',
sku: ‘tvluong.EndlessHaiku’
)
cert
sigh(force: true)
end

lane :screenshot do
snapshot
frameit
end

lane :deliver do
deliver
end

end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
